apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-example-deployment
  labels:
    app: env-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: env-example
  template:
    metadata:
      labels:
        app: env-example
    spec:
      containers:
      - name: web
        image: akalipetis/env-example
        ports:
        - containerPort: 5000
          name: web
        resources:
          limits:
            memory: 512Mi
            cpu: 0.5
          requests:
            memory: 384Mi
            cpu: 0.25
---
apiVersion: v1
kind: Service
metadata:
  name: env-example-svc
spec:
  type: NodePort
  selector:
    app: env-example
  ports:
  - protocol: TCP
    port: 5000
    targetPort: web
