kind: Deployment
apiVersion: apps/v1
metadata:
  name: ceryx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceryx
  template:
    metadata:
      labels:
        app: ceryx
    spec:
      containers:
        - name: ceryx
          image: sourcelair/ceryx:v0.1.3
          env:
            - name: CERYX_REDIS_HOST
              value: ceryx-redis.default.svc.cluster.local
            - name: CERYX_REDIS_PORT
              value: '6379'
            - name: CERYX_SSL_PATTERN
              value: ''
            - name: CERYX_FALLBACK
              value: 404.apps.lair.io
            - name: CERYX_DNS_RESOLVER
              value: 10.96.0.10
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ceryx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceryx-api
  template:
    metadata:
      labels:
        app: ceryx-api
    spec:
      containers:
        - name: api
          image: sourcelair/ceryx-api:latest
          env:
            - name: CERYX_API_HOST
              value: '0.0.0.0'
            - name: CERYX_REDIS_HOST
              value: ceryx-redis.default.svc.cluster.local
            - name: CERYX_REDIS_PORT
              value: '6379'
            - name: CERYX_API_PORT
              value: '5555'
            - name: CERYX_API_HOSTNAME
              value: ceryx_api
            - name: CERYX_DEBUG
              value: 'false'
          ports:
            - containerPort: 5555
              name: web
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ceryx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceryx-web
  template:
    metadata:
      labels:
        app: ceryx-web
    spec:
      containers:
        - name: web
          image: paris/ceryx-web:latest
          env:
            - name: CERYX_API_HOST
              value: http://ceryx-api
          ports:
            - containerPort: 5000
              name: web
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ceryx-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceryx-redis
  template:
    metadata:
      labels:
        app: ceryx-redis
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        ports:
          - containerPort: 6379
            name: redis
